services:
  tarsforge:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
      - VITE_MODAL_MODEL=${VITE_MODAL_MODEL:-nemotron-3-super:cloud}
      - VITE_MODAL_MODEL2=${VITE_MODAL_MODEL2:-minimax-m2.7:cloud}
    labels:
      - traefik.enable=true
      - traefik.http.routers.tarsforge.rule=Host(`tarsforge.sebastianmorales.sbs`)
      - 'traefik.http.routers.tarsforge.entryPoints=http,https'
      - traefik.http.routers.tarsforge.tls=true
      - traefik.http.services.tarsforge.loadbalancer.server.port=3000
    restart: unless-stopped

networks:
  coolify:
    external: true